### ISSUE TITLE
Implement bubble sort 

### ISSUE THREAD

**Issue by DheerendraRathor** [DheerendraRathor/Python-Algorithms#3]
Add a file bubble_sort.py which implements bubble sort with test cases.

**Comment by pjbollinger** [comment]
I would like to take a crack at this. 😄

**Comment by DheerendraRathor** [comment]
@pjbollinger Sure, go ahead. Make sure you add test cases and update README.

**Comment by DheerendraRathor** [comment]
Resolved by #4
